/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fcl_jni_PdfiumJNI */

#ifndef _Included_com_fcl_jni_PdfiumJNI
#define _Included_com_fcl_jni_PdfiumJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_SUCCESS
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_SUCCESS 0L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_UNKNOWN
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_UNKNOWN 1L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_FILE
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_FILE 2L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_FORMAT
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_FORMAT 3L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_PASSWORD
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_PASSWORD 4L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_SECURITY
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_SECURITY 5L
#undef com_fcl_jni_PdfiumJNI_FPDF_ERR_PAGE
#define com_fcl_jni_PdfiumJNI_FPDF_ERR_PAGE 6L
#undef com_fcl_jni_PdfiumJNI_ROTATE_0
#define com_fcl_jni_PdfiumJNI_ROTATE_0 0L
#undef com_fcl_jni_PdfiumJNI_ROTATE_90
#define com_fcl_jni_PdfiumJNI_ROTATE_90 1L
#undef com_fcl_jni_PdfiumJNI_ROTATE_180
#define com_fcl_jni_PdfiumJNI_ROTATE_180 2L
#undef com_fcl_jni_PdfiumJNI_ROTATE_270
#define com_fcl_jni_PdfiumJNI_ROTATE_270 3L
#undef com_fcl_jni_PdfiumJNI_FPDF_ANNOT
#define com_fcl_jni_PdfiumJNI_FPDF_ANNOT 1L
#undef com_fcl_jni_PdfiumJNI_FPDF_LCD_TEXT
#define com_fcl_jni_PdfiumJNI_FPDF_LCD_TEXT 2L
#undef com_fcl_jni_PdfiumJNI_FPDF_NO_NATIVETEXT
#define com_fcl_jni_PdfiumJNI_FPDF_NO_NATIVETEXT 4L
#undef com_fcl_jni_PdfiumJNI_FPDF_GRAYSCALE
#define com_fcl_jni_PdfiumJNI_FPDF_GRAYSCALE 8L
#undef com_fcl_jni_PdfiumJNI_FPDF_RENDER_LIMITEDIMAGECACHE
#define com_fcl_jni_PdfiumJNI_FPDF_RENDER_LIMITEDIMAGECACHE 512L
#undef com_fcl_jni_PdfiumJNI_FPDF_RENDER_FORCEHALFTONE
#define com_fcl_jni_PdfiumJNI_FPDF_RENDER_FORCEHALFTONE 1024L
#undef com_fcl_jni_PdfiumJNI_FPDF_PRINTING
#define com_fcl_jni_PdfiumJNI_FPDF_PRINTING 2048L
#undef com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHTEXT
#define com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHTEXT 4096L
#undef com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHIMAGE
#define com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHIMAGE 8192L
#undef com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHPATH
#define com_fcl_jni_PdfiumJNI_FPDF_RENDER_NO_SMOOTHPATH 16384L
#undef com_fcl_jni_PdfiumJNI_FPDF_REVERSE_BYTE_ORDER
#define com_fcl_jni_PdfiumJNI_FPDF_REVERSE_BYTE_ORDER 16L
#undef com_fcl_jni_PdfiumJNI_FPDFBitmap_Unknown
#define com_fcl_jni_PdfiumJNI_FPDFBitmap_Unknown 0L
#undef com_fcl_jni_PdfiumJNI_FPDFBitmap_Gray
#define com_fcl_jni_PdfiumJNI_FPDFBitmap_Gray 1L
#undef com_fcl_jni_PdfiumJNI_FPDFBitmap_BGR
#define com_fcl_jni_PdfiumJNI_FPDFBitmap_BGR 2L
#undef com_fcl_jni_PdfiumJNI_FPDFBitmap_BGRx
#define com_fcl_jni_PdfiumJNI_FPDFBitmap_BGRx 3L
#undef com_fcl_jni_PdfiumJNI_FPDFBitmap_BGRA
#define com_fcl_jni_PdfiumJNI_FPDFBitmap_BGRA 4L
/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    initLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_initLibrary
  (JNIEnv *, jclass);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    destroyLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_destroyLibrary
  (JNIEnv *, jclass);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    loadDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_loadDocument
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    loadMemDocument
 * Signature: ([BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_loadMemDocument___3BLjava_lang_String_2
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    loadMemDocument
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_loadMemDocument__Ljava_nio_ByteBuffer_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    closeDocument
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_closeDocument
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getPageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_fcl_jni_PdfiumJNI_getPageCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getFileVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_fcl_jni_PdfiumJNI_getFileVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getDocPermissions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_getDocPermissions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fcl_jni_PdfiumJNI_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    loadPage
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_loadPage
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    closePage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_closePage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getPageWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_fcl_jni_PdfiumJNI_getPageWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getPageHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_fcl_jni_PdfiumJNI_getPageHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getPageSizeByIndex
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_fcl_jni_PdfiumJNI_getPageSizeByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    createBitmap
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_createBitmap
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    createBitmapEx
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_fcl_jni_PdfiumJNI_createBitmapEx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    destroyBitmap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_destroyBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    fillRect
 * Signature: (JIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fcl_jni_PdfiumJNI_fillRect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getBitmapBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_fcl_jni_PdfiumJNI_getBitmapBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    getBitmapStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_fcl_jni_PdfiumJNI_getBitmapStride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    renderPageBitmap
 * Signature: (JJIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_fcl_jni_PdfiumJNI_renderPageBitmap
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    deviceToPage
 * Signature: (JIIIIIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_fcl_jni_PdfiumJNI_deviceToPage
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_fcl_jni_PdfiumJNI
 * Method:    pageToDevice
 * Signature: (JIIIIIDD)[I
 */
JNIEXPORT jintArray JNICALL Java_com_fcl_jni_PdfiumJNI_pageToDevice
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
